jobs:
  build:tools:
    executor: local
    commands:
      - docker build -t tools _tools/

  benchmark:
    executor: local
    variables:
      DOCKER_BUILDKIT: "0"
    commands:
      - SESSION=".sessions/${WERK_SESSION_ID}"
      - mkdir -p "${SESSION}"
      - |
        for SOLUTION in $(find Prime* -type f -name Dockerfile -exec dirname {} \;| sed -e 's|^./||' | sort)
        do
          NAME=$(echo "${SOLUTION}" | sed -r 's/\//-/g' | tr '[:upper:]' '[:lower:]')
          
          echo "[*] Building: ${NAME}"
          docker build -q -t "${NAME}" "${SOLUTION}" || continue

          echo "[*] Running: ${NAME}"
          docker run --rm "${NAME}" > "${SESSION}/${NAME}.out" || continue
        done

  report:
    executor: docker
    image: tools
    commands:
      - SESSION=".sessions/${WERK_SESSION_ID}"
      - report.py -d "${SESSION}"
    needs:
      - build:tools
      - benchmark