[package]
name = "prime_sieve_rust"
version = "0.1.0"
authors = ["Stephen Newman <steve@newman.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stopwatch = "0.0.7"