WORKDIR /home/sieve

# Copy all shell scripts, C source, and header files
COPY src/ ./src/
COPY sieve ./sieve

# Ensure the bin directory exists
RUN mkdir -p bin dev/build && \
    chmod +x ./sieve && \
    sed -i 's/\r$//' ./sieve

RUN ./sieve compileall

ENTRYPOINT [ "./sieve" ]
