FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && apt-get install -y build-essential clang llvm libomp-dev \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
