FROM alpine:3.21.3

# Install necessary dependencies
RUN apk add --no-cache build-base clang openmp-dev bash wget git

# Download and build Hoard memory allocator
WORKDIR /tmp
RUN git clone https://github.com/emeryberger/Hoard.git && \
    cd Hoard/src && \
    make && \
    cp libhoard.so /usr/lib/

# Set Hoard as the default memory allocator using LD_PRELOAD
ENV LD_PRELOAD=/usr/lib/libhoard.so
