FROM ubuntu:24.04

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository ppa:ubuntu-toolchain-r/test -y \
    && apt-get update \
    && apt-get install -y build-essential gcc-14 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
