FROM alpine:3.21.3

# Install necessary dependencies
RUN apk add build-base openmp-dev bash jemalloc

# Set mimalloc as the default memory allocator using LD_PRELOAD
ENV LD_PRELOAD=/usr/lib/libjemalloc.so.2


