;;;; SPDX-License-Identifier: BSD-3-Clause
;;;; SBCL 2.6.8, Linux x86-64 with AVX2. One bit per odd candidate.
;;;; Native allocation/free, SIMD masks hoisted outside loops, cache blocking.
;;;; Dense/sparse patterns follow Mike Barber and GordonBGood (PrimeRust/solution_1).
;;;; No prime list or sieve result is precomputed. See README.md for the algorithm and development approach.
(defpackage #:prime-memory
  (:use #:cl) (:nicknames #:pm)
  (:export #:with-sieve #:run-sieve #:primep #:count-primes #:*name* #:*tags*))
(in-package #:prime-memory)
(declaim (optimize (speed 3) (safety 0) (debug 1)))
(declaim (sb-ext:muffle-conditions sb-ext:compiler-note))
(defparameter *name* "echologie-cl-native-avx2-block32k")
(defparameter *tags* "algorithm=other,faithful=yes,bits=1")
(defun checked-limit (limit)
  (declare (optimize (safety 3)))
  (check-type limit (integer 0 #.most-positive-fixnum))
  limit)
(defun or-byte! (sap offset mask)
  (declare (type sb-sys:system-area-pointer sap)
           (type (signed-byte 64) offset) (type (unsigned-byte 8) mask))
  (setf (sb-sys:sap-ref-8 sap offset)
        (logior (sb-sys:sap-ref-8 sap offset) mask))
  (values))
(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown or-byte! (sb-sys:system-area-pointer (signed-byte 64) (unsigned-byte 8))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (or-byte!)
    (:translate or-byte!)
    (:policy :fast-safe)
    (:args (sap :scs (sb-vm::sap-reg)) (offset :scs (sb-vm::signed-reg)))
    (:arg-types sb-vm::system-area-pointer sb-vm::signed-num (:constant (unsigned-byte 8)))
    (:info mask)
    (:generator 1
      (sb-assem:inst or :byte (sb-vm::ea 0 sap offset) mask))))


(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown sparse-kernel! (sb-sys:system-area-pointer (unsigned-byte 64) (unsigned-byte 64) (unsigned-byte 64) (integer 1 15))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (sparse-kernel!)
    (:translate sparse-kernel!) (:policy :fast-safe)
    ;; Keep inputs live until all temporary-register computations finish.
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (blocks :scs (sb-vm::unsigned-reg) :to :save)
           (q :scs (sb-vm::unsigned-reg) :to :save)
           (step :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num sb-vm::unsigned-num sb-vm::unsigned-num (:constant (integer 1 15)))
    (:info residue)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining q3 q5 q7)
    (:generator 1
      (let ((again (sb-assem:gen-label)) (done (sb-assem:gen-label)))
        (sb-vm::move ptr sap)
        (sb-vm::move remaining blocks)
        (sb-assem:inst test remaining remaining)
        (sb-assem:inst jmp :z done)
        (sb-assem:inst lea q3 (sb-vm::ea 0 q q 2))
        (sb-assem:inst lea q5 (sb-vm::ea 0 q q 4))
        (sb-assem:inst lea q7 (sb-vm::ea 0 q3 q 4))
        (sb-assem:emit-label again)
        (loop for k below 8 for index in (list nil q q q3 q q5 q3 q7)
              for scale in '(1 1 2 1 4 1 2 1)
              for carry = (floor (+ (floor residue 2) (* k (mod residue 8))) 8)
              for mask = (ash 1 (mod (+ (floor residue 2) (* k residue)) 8))
              do (sb-assem:inst or :byte (sb-vm::ea carry ptr index scale) mask))
        (sb-assem:inst add ptr step)
        (sb-assem:inst dec remaining)
        (sb-assem:inst jmp :nz again)
        (sb-assem:emit-label done)))))

(sb-alien:define-alien-routine ("malloc" native-malloc) sb-alien:unsigned-long
  (size sb-alien:unsigned-long))
(sb-alien:define-alien-routine ("free" native-free) sb-alien:void
  (address sb-alien:unsigned-long))
(sb-alien:define-alien-routine ("memset" native-memset) sb-alien:unsigned-long
  (address sb-alien:unsigned-long) (value sb-alien:int) (size sb-alien:unsigned-long))
(declaim (inline make-foreign-state))
(defstruct foreign-state
  (limit 0 :type fixnum) (nwords 0 :type fixnum)
  (address 0 :type (unsigned-byte 64)))
(defmacro with-foreign-state ((state limit) &body body)
  (let ((n (gensym)) (nwords (gensym)) (address (gensym)))
    `(let* ((,n (checked-limit ,limit)) (,nwords (ceiling (ceiling ,n 2) 64))
            (,address (native-malloc (max 8 (* ,nwords 8)))))
       (declare (type fixnum ,n ,nwords) (type (unsigned-byte 64) ,address))
       (when (zerop ,address) (error "Native allocation failed."))
       (unwind-protect
            (let ((,state (make-foreign-state :limit ,n :nwords ,nwords :address ,address)))
              (declare (dynamic-extent ,state))
              (native-memset ,address 0 (* ,nwords 8))
              (when (plusp ,nwords) (setf (sb-sys:sap-ref-64 (sb-sys:int-sap ,address) 0) 1))
              ,@body)
         (native-free ,address)))))
(declaim (inline foreign-marked-p))
(defun foreign-marked-p (address index)
  (declare (type (unsigned-byte 64) address) (type fixnum index))
  (logbitp (logand index 63)
           (sb-sys:sap-ref-64 (sb-sys:int-sap address) (ash (ash index -6) 3))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown avx-dense! (sb-sys:system-area-pointer (unsigned-byte 64) (integer 3 129))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (avx-dense!)
    (:translate avx-dense!) (:policy :fast-safe)
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (nwords :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num (:constant (integer 3 129)))
    (:info factor)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining scalar)
    (:temporary (:sc sb-vm::int-avx2-reg) m0 m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 tmp)
    (:generator 1
      (let* ((masks (make-array factor :initial-element 0))
             (first (* factor (floor factor 128)))
             (block (* factor (if (<= factor 7) 4 1)))
             (nvectors (floor block 4))
             (registers (list m0 m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14))
             (again (sb-assem:gen-label)) (tail (sb-assem:gen-label)))
        (dotimes (k 64)
          (let ((bit (+ (floor factor 2) (* k factor))))
            (setf (aref masks (floor bit 64))
                  (logior (aref masks (floor bit 64)) (ash 1 (mod bit 64))))))
        (let ((constants
                (loop for i below nvectors collect
                  (sb-c:register-inline-constant :avx2
                    (loop for lane below 4 sum
                      (ash (aref masks (mod (+ (* i 4) lane) factor)) (* lane 64)))))))
          (sb-assem:inst lea ptr (sb-vm::ea (* first 8) sap))
          (sb-vm::move remaining nwords)
          (unless (zerop first) (sb-assem:inst sub remaining first))
          (sb-assem:inst cmp remaining block)
          (sb-assem:inst jmp :b tail)
          (loop for reg in registers for constant in constants
                do (sb-assem:inst vmovdqu reg constant))
          (flet ((word (i)
                   (let ((mask (aref masks (mod i factor))))
                     (unless (zerop mask)
                       (if (typep mask '(signed-byte 32))
                           (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) mask)
                           (progn (sb-assem:inst mov scalar mask)
                                  (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) scalar)))))))
            (sb-assem:emit-label again)
            (dotimes (i nvectors)
              (if (< i (length registers))
                  (sb-assem:inst vpor tmp (nth i registers) (sb-vm::ea (* i 32) ptr))
                  (progn (sb-assem:inst vmovdqu tmp (sb-vm::ea (* i 32) ptr))
                         (sb-assem:inst vpor tmp tmp (nth i constants))))
              (sb-assem:inst vmovdqu (sb-vm::ea (* i 32) ptr) tmp))
            (loop for i from (* nvectors 4) below block do (word i))
            (sb-assem:inst add ptr (* block 8))
            (sb-assem:inst sub remaining block)
            (sb-assem:inst cmp remaining block)
            (sb-assem:inst jmp :ae again)
            (sb-assem:emit-label tail)
            (dotimes (i block)
              (unless (zerop (aref masks (mod i factor)))
                (let ((skip (sb-assem:gen-label)))
                  (sb-assem:inst cmp remaining i)
                  (sb-assem:inst jmp :be skip)
                  (word i) (sb-assem:emit-label skip)))))
          (let ((bit (floor factor 2)))
            (sb-assem:inst mov scalar (logxor #xffffffffffffffff (ash 1 (mod bit 64))))
            (sb-assem:inst and :qword (sb-vm::ea (* 8 (floor bit 64)) sap) scalar))
          (sb-assem:inst vzeroupper))))))

(eval-when (:compile-toplevel :load-toplevel :execute)
  (sb-c:defknown avx-block-dense! (sb-sys:system-area-pointer (unsigned-byte 64) (integer 3 129))
      (values) (sb-c:always-translatable) :overwrite-fndb-silently t)
  (sb-c:define-vop (avx-block-dense!)
    (:translate avx-block-dense!) (:policy :fast-safe)
    (:args (sap :scs (sb-vm::sap-reg) :to :save)
           (nwords :scs (sb-vm::unsigned-reg) :to :save))
    (:arg-types sb-vm::system-area-pointer sb-vm::unsigned-num (:constant (integer 3 129)))
    (:info factor)
    (:temporary (:sc sb-vm::sap-reg) ptr)
    (:temporary (:sc sb-vm::unsigned-reg) remaining scalar)
    (:temporary (:sc sb-vm::int-avx2-reg) m0 m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14 tmp)
    (:generator 1
      (let* ((masks (make-array factor :initial-element 0))
             (first 0)
             (block (* factor (if (<= factor 7) 4 1)))
             (nvectors (floor block 4))
             (registers (list m0 m1 m2 m3 m4 m5 m6 m7 m8 m9 m10 m11 m12 m13 m14))
             (again (sb-assem:gen-label)) (tail (sb-assem:gen-label)))
        (dotimes (k 64)
          (let ((bit (+ (floor factor 2) (* k factor))))
            (setf (aref masks (floor bit 64))
                  (logior (aref masks (floor bit 64)) (ash 1 (mod bit 64))))))
        (let ((constants
                (loop for i below nvectors collect
                  (sb-c:register-inline-constant :avx2
                    (loop for lane below 4 sum
                      (ash (aref masks (mod (+ (* i 4) lane) factor)) (* lane 64)))))))
          (sb-assem:inst lea ptr (sb-vm::ea (* first 8) sap))
          (sb-vm::move remaining nwords)
          (unless (zerop first) (sb-assem:inst sub remaining first))
          (sb-assem:inst cmp remaining block)
          (sb-assem:inst jmp :b tail)
          (loop for reg in registers for constant in constants
                do (sb-assem:inst vmovdqu reg constant))
          (flet ((word (i)
                   (let ((mask (aref masks (mod i factor))))
                     (unless (zerop mask)
                       (if (typep mask '(signed-byte 32))
                           (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) mask)
                           (progn (sb-assem:inst mov scalar mask)
                                  (sb-assem:inst or :qword (sb-vm::ea (* i 8) ptr) scalar)))))))
            (sb-assem:emit-label again)
            (dotimes (i nvectors)
              (if (< i (length registers))
                  (sb-assem:inst vpor tmp (nth i registers) (sb-vm::ea (* i 32) ptr))
                  (progn (sb-assem:inst vmovdqu tmp (sb-vm::ea (* i 32) ptr))
                         (sb-assem:inst vpor tmp tmp (nth i constants))))
              (sb-assem:inst vmovdqu (sb-vm::ea (* i 32) ptr) tmp))
            (loop for i from (* nvectors 4) below block do (word i))
            (sb-assem:inst add ptr (* block 8))
            (sb-assem:inst sub remaining block)
            (sb-assem:inst cmp remaining block)
            (sb-assem:inst jmp :ae again)
            (sb-assem:emit-label tail)
            (dotimes (i block)
              (unless (zerop (aref masks (mod i factor)))
                (let ((skip (sb-assem:gen-label)))
                  (sb-assem:inst cmp remaining i)
                  (sb-assem:inst jmp :be skip)
                  (word i) (sb-assem:emit-label skip)))))
          (sb-assem:inst vzeroupper))))))


(defmacro define-foreign-resetters ()
  `(progn
     ,@(loop for p from 3 to 129 by 2 collect
       `(defun ,(intern (format nil "FOREIGN-DENSE-~D" p)) (address nwords)
          (declare (type (unsigned-byte 64) address) (type fixnum nwords))
          (avx-dense! (sb-sys:int-sap address) nwords ,p)
          nil))
     (defun foreign-dense-reset (address nwords factor)
       (declare (type (unsigned-byte 64) address) (type fixnum nwords factor))
       (case factor ,@(loop for p from 3 to 129 by 2 collect
         `(,p (,(intern (format nil "FOREIGN-DENSE-~D" p)) address nwords)))))
     ,@(loop for r from 1 to 15 by 2 collect
       `(defun ,(intern (format nil "FOREIGN-SPARSE-~D" r)) (address nbytes factor)
          (declare (type (unsigned-byte 64) address) (type fixnum nbytes)
                   (type (integer 3 2147483647) factor))
          (let* ((first (ash factor -4)) (start (* first factor)) (q (ash factor -3))
                 (blocks (floor (- nbytes start) factor))
                 (tail (+ start first (* blocks factor)))
                 (sap (sb-sys:int-sap address)))
            (declare (type (unsigned-byte 59) first start q blocks tail))
            (sparse-kernel! (sb-sys:sap+ sap (+ start first)) blocks q factor ,r)
            ,@(loop for k below 8
               for carry = (floor (+ (floor r 2) (* k (mod r 8))) 8)
               for mask = (ash 1 (mod (+ (floor r 2) (* k r)) 8))
               collect `(let ((index (+ tail (* ,k q) ,carry)))
                          (declare (type (unsigned-byte 59) index))
                          (when (< index nbytes) (or-byte! sap index ,mask)))))
          nil))
     (defun foreign-sparse-reset (address nbytes factor)
       (declare (type (unsigned-byte 64) address) (type fixnum nbytes factor))
       (case (logand factor 15) ,@(loop for r from 1 to 15 by 2 collect
          `(,r (,(intern (format nil "FOREIGN-SPARSE-~D" r)) address nbytes factor)))))))
(define-foreign-resetters)

(defmacro define-block-resetters ()
  `(progn
     ,@(loop for p from 3 to 129 by 2 collect
       `(defun ,(intern (format nil "BLOCK-DENSE-~D" p)) (address nwords)
          (declare (type (unsigned-byte 64) address) (type fixnum nwords))
          (avx-block-dense! (sb-sys:int-sap address) nwords ,p)
          nil))
     (defun block-dense-reset (address nwords factor)
       (declare (type (unsigned-byte 64) address) (type fixnum nwords factor))
       (case factor ,@(loop for p from 3 to 129 by 2 collect
         `(,p (,(intern (format nil "BLOCK-DENSE-~D" p)) address nwords)))))
     ,@(loop for r from 1 to 15 by 2 collect
       `(defun ,(intern (format nil "BLOCK-SPARSE-~D" r)) (address begin nbytes factor)
          (declare (type (unsigned-byte 64) address) (type fixnum begin nbytes)
                   (type (integer 3 2147483647) factor))
          (let* ((first (ash factor -4))
                 (start (max (* first factor) (* (floor begin factor) factor)))
                 (q (ash factor -3)) (blocks (floor (- nbytes start) factor))
                 (tail (+ start first (* blocks factor)))
                 (sap (sb-sys:int-sap address)))
            (declare (type (unsigned-byte 59) first start q blocks tail))
            (sparse-kernel! (sb-sys:sap+ sap (+ start first)) blocks q factor ,r)
            ,@(loop for k below 8
               for carry = (floor (+ (floor r 2) (* k (mod r 8))) 8)
               for mask = (ash 1 (mod (+ (floor r 2) (* k r)) 8))
               collect `(let ((index (+ tail (* ,k q) ,carry)))
                          (declare (type (unsigned-byte 59) index))
                          (when (< index nbytes) (or-byte! sap index ,mask)))))
          nil))
     (defun block-sparse-reset (address begin nbytes factor)
       (declare (type (unsigned-byte 64) address) (type fixnum begin nbytes factor))
       (case (logand factor 15) ,@(loop for r from 1 to 15 by 2 collect
          `(,r (,(intern (format nil "BLOCK-SPARSE-~D" r)) address begin nbytes factor)))))))
(define-block-resetters)
(defparameter *block-words* 4096)
(defun run-foreign-state (state)
  (let ((address (foreign-state-address state)) (nwords (foreign-state-nwords state))
        (limit (foreign-state-limit state)) (block-size *block-words*))
    (declare (type fixnum block-size))
    ;; The first block determines the factors by sieving, with no stored prime list.
    ;; For supported sizes (<=10 million), every factor flag lies in the first block.
    (assert (>= (* block-size 128) (isqrt limit)))
    (loop for begin fixnum from 0 below nwords by block-size
          for end fixnum = (min nwords (+ begin block-size)) do
      (loop for factor fixnum from 3 to (isqrt (min limit (* end 128))) by 2
            unless (foreign-marked-p address (ash factor -1)) do
        (cond ((zerop begin)
               (if (<= factor 129) (foreign-dense-reset address end factor)
                   (foreign-sparse-reset address (ash end 3) factor)))
              ((<= factor 129)
               ;; A bounded overlap preserves the factor's repeating mask phase.
               ;; Only composites are written; no prime bit is cleared in later blocks.
               (let ((base (* (floor begin factor) factor)))
                 (declare (type fixnum base))
                 (block-dense-reset (+ address (ash base 3)) (- end base) factor)))
              (t (block-sparse-reset address (ash begin 3) (ash end 3) factor))))))
  state)

(defun foreign-prime-p (state number)
  (declare (type fixnum number))
  (and (<= 2 number (foreign-state-limit state))
       (or (= number 2) (and (oddp number)
         (not (foreign-marked-p (foreign-state-address state) (ash number -1)))))))
(defun foreign-count (state)
  (let* ((limit (foreign-state-limit state)) (sap (sb-sys:int-sap (foreign-state-address state)))
         (nbits (ceiling limit 2)) (nwords (ash nbits -6)) (tail (logand nbits 63)))
    (declare (type fixnum limit nbits nwords tail))
    (+ (if (>= limit 2) 1 0)
       (- nbits (+ (loop for i fixnum below nwords sum
                   (logcount (sb-sys:sap-ref-64 sap (ash i 3))) fixnum)
                  (if (zerop tail) 0
                    (logcount (logand (sb-sys:sap-ref-64 sap (ash nwords 3))
                                     (1- (ash 1 tail))))))))))


(defmacro with-sieve ((state limit) &body body)
  "Create fresh state; release native memory on normal and nonlocal exits.
STATE and its address must not escape BODY. No finalizer or GC is needed."
  `(with-foreign-state (,state ,limit) ,@body))
(declaim (inline run-sieve primep count-primes))
(defun run-sieve (state) (run-foreign-state state))
(defun primep (state number) (foreign-prime-p state number))
(defun count-primes (state) (foreign-count state))
