Dyalog APL is licensed software.  Installations of Dyalog include Dyalog APL, some third party software, and a number of tools each of which have licences associated with them.

For more information please see the "Dyalog_Developer_Software_Licence.pdf" in the help directory or online at https://www.dyalog.com/uploads/documents/Developer_Software_Licence.pdf for the Developer Licence information for Dyalog APL, the “Licences for third-party components.docx” in the help directory, and the various LICENSE files that are to be found in various subdirectories in the Dyalog installation.  

Please note that each of the licences in the LICENSE files apply only to the contents of the directory in which they are found, and any subdirectories thereof.

